//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GonharovCafeKK.AppFolder.EntityFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int MenuID { get; set; }
        public string NameDish { get; set; }
        public byte[] Photo { get; set; }
        public int Price { get; set; }
        public string Composition { get; set; }
        public Nullable<int> WeightDishGR { get; set; }
        public Nullable<double> Calories { get; set; }
        public Nullable<double> Fat { get; set; }
        public Nullable<double> Protein { get; set; }
        public Nullable<double> Carb { get; set; }
        public bool isNew { get; set; }
        public bool isHit { get; set; }
        public bool isSeason { get; set; }
        public int DishCategoryID { get; set; }
    
        public virtual DishCategory DishCategory { get; set; }
    }
}
