//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GonharovCafeKK.AppFolder.EntityFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string DishOrder { get; set; }
        public int Price { get; set; }
        public System.DateTime DateOfReceiving { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public Nullable<int> UserID { get; set; }
        public int StatusID { get; set; }
    
        public virtual StatusOrder StatusOrder { get; set; }
        public virtual User User { get; set; }
    }
}
